import React from "react";
import {
    LineChart,
    Line,
    XAxis,
    YAxis,
    CartesianGrid,
    Tooltip,
    ResponsiveContainer,
    ReferenceLine,
    Area,
    AreaChart,
    ReferenceArea
} from "recharts";
import { useSimStore } from "../../store/useSimStore";

export function SocialPremiumChart() {
    const history = useSimStore((state) => state.socialPremiumHistory);

    return (
        <div className="w-full h-full flex flex-col">
            <div className="flex items-center justify-between mb-4">
                <div>
                    <h2 className="text-lg font-bold text-slate-100 italic">Social Premium</h2>
                    <p className="text-xs text-slate-500">Value generated by tokens vs fiat equivalent</p>
                </div>
                <div className="text-right">
                    <span className="text-2xl font-mono font-bold text-emerald-400">
                        {history.length > 0 ? history[history.length - 1].value.toFixed(2) : "0.00"}x
                    </span>
                </div>
            </div>

            <div className="flex-1 min-h-[300px]">
                <ResponsiveContainer width="100%" height="100%">
                    <AreaChart data={history} margin={{ top: 10, right: 10, left: 0, bottom: 0 }}>
                        <defs>
                            <linearGradient id="premiumGradient" x1="0" y1="0" x2="0" y2="1">
                                <stop offset="5%" stopColor="#10b981" stopOpacity={0.3} />
                                <stop offset="95%" stopColor="#10b981" stopOpacity={0} />
                            </linearGradient>
                        </defs>
                        <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" vertical={false} />
                        <XAxis
                            dataKey="tick"
                            stroke="#475569"
                            fontSize={10}
                            tickLine={false}
                            axisLine={false}
                            tickFormatter={(val) => `D${val}`}
                        />
                        <YAxis
                            stroke="#475569"
                            fontSize={10}
                            tickLine={false}
                            axisLine={false}
                            domain={[0, (dataMax) => Math.max(2, dataMax + 0.5)]}
                            tickFormatter={(val) => `${val}x`}
                        />
                        <Tooltip
                            contentStyle={{ backgroundColor: "#0f172a", border: "1px solid #1e293b", borderRadius: "8px" }}
                            itemStyle={{ color: "#10b981", fontSize: "12px", fontWeight: "bold" }}
                            labelStyle={{ color: "#64748b", fontSize: "10px", marginBottom: "4px" }}
                            formatter={(value) => [`${value.toFixed(2)}x`, "Premium"]}
                            labelFormatter={(label) => `Tick ${label}`}
                        />
                        <ReferenceArea y1={1} y2={5} fill="#064e3b" fillOpacity={0.05} />
                        <ReferenceArea y1={0} y2={1} fill="#7f1d1d" fillOpacity={0.05} />
                        <ReferenceLine y={1} stroke="#ef4444" strokeDasharray="3 3" label={{ position: 'right', value: 'Parity', fill: '#ef4444', fontSize: 10 }} />
                        <Area
                            type="monotone"
                            dataKey="value"
                            stroke="#10b981"
                            strokeWidth={3}
                            fillOpacity={1}
                            fill="url(#premiumGradient)"
                            animationDuration={500}
                        />
                    </AreaChart>
                </ResponsiveContainer>
            </div>
        </div>
    );
}
